lexer: clang -g -O0 -o src/parser/test/lexer_test.t src/parser/test/lexer_test.c -I /usr/local/include/google/ -lcmockery \
	./src/parser/test/lexer_test.t

parser: clang -g -O0 -o src/parser/test/parser_test.t src/parser/test/lexer_test.c src/utils/list.c -I /usr/local/include/google/ -lcmockery \
	./src/parser/test/parser_test.t

